### ISSUE TITLE
Publishing a new minor version

### ISSUE THREAD

**Issue by petrochenkov** [milibopp/carboxyl_time#4]
Hi.
https://github.com/rust-lang/rust/pull/42125 is going to turn some old compatibility "private-in-public" warnings in `rustc` into hard errors.
`crates.io` testing discovered that published version of this crate is affected by one of those errors.
The current master is building successfully with https://github.com/rust-lang/rust/pull/42125, could you push it on crates.io as `carboxyl_time-0.0.3`?
(Even if the crate is deprecated, it would still be useful for the compiler's regression testing.)

**Comment by milibopp** [comment]
Sure, I will do so as soon as possible.
